spring:
  mvc:
    static-path-pattern: /static/**
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/BETTERNOW?serverTimezone=UTC&characterEncoding=UTF-8
    username: KSH
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    database: mysql
    hibernate:
      use-new-id-generator-mappings: false

